CREATE DATABASE LOGIN_FORM;
CREATE TABLE LOGIN_TBL
(
USERNAME VARCHAR(50) NOT NULL,
PASS NVARCHAR(50) NOT NULL
);



SELECT * FROM LOGIN_TBL;
INSERT INTO LOGIN_TBL VALUES('NASIM', '0101');
INSERT INTO LOGIN_TBL VALUES('ISLAM', '0202');
INSERT INTO LOGIN_TBL VALUES('TANMOY', '0303');
INSERT INTO LOGIN_TBL VALUES('RUHUL', '0404');
